exclude: ^docs/changelog\.md$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff # Run linter using pyproject.toml config
      - id: ruff-format # Run formatter using pyproject.toml config

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.5
    hooks:
      - id: uv-lock
