site_name: eo-tides
repo_url: https://github.com/GeoscienceAustralia/eo-tides
site_url: https://GeoscienceAustralia.github.io/eo-tides
site_description: eo-tides - Tide modelling tools for large-scale satellite earth observation analysis
site_author: Robbi Bishop-Taylor
edit_uri: edit/main/docs/
repo_name: GeoscienceAustralia/eo-tides
copyright: Maintained by Robbi Bishop-Taylor (@satellitesci)

nav:
  - Home: index.md
  - Installation: install.md
  - Setting up tide models: setup.md
  - Usage:
      - notebooks/Model_tides.ipynb
      - notebooks/Satellite_data.ipynb
      - notebooks/Tide_statistics.ipynb
      - notebooks/Validating_tides.ipynb
  - Case study examples:
      - notebooks/Case_study_intertidal.ipynb
  - Developer guide:
      - API reference: api.md
  - Reference:
      - Changelog: changelog.md
      - Migrating from DEA Tools: migration.md
      - Citations and credits: credits.md

plugins:
  - search
  - mkdocs-jupyter:
      # execute: true
      # execute_ignore:
      #   - notebooks/Model_tides.ipynb
      #   - notebooks/Satellite_data.ipynb
      #   - notebooks/Tide_statistics.ipynb
      #   - notebooks/Validating_tides.ipynb
      #   - notebooks/Case_study_intertidal.ipynb
  - mkdocstrings:
      handlers:
        python:
          paths: ["eo_tides"]
          options:
            docstring_style: numpy
            # docstring_options:
            #   ignore_init_summary: true
            # docstring_section_style: list
            filters: ["!^_"]
            # heading_level: 1
            # inherited_members: true
            # merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            line_length: 60
            show_root_heading: true
            # show_category_heading: true
            # show_root_full_path: true
            # show_root_members_full_path: true
            # show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            # group_by_category: true
            # signature_crossrefs: true
            summary: true

theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: eotides
      primary: white
      accent: deep orange
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  logo: assets/eo-tides-logo-128.png
  favicon: assets/eo-tides-logo-128.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - content.code.copy
  #   - announce.dismiss
  #   - navigation.instant
  #   - navigation.tracking
  #   - navigation.tabs

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GeoscienceAustralia/eo-tides
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/eo-tides
  announce:
    content: Your announcement text goes here

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
