name: "Setup Python Environment"
description: "Set up Python environment for the given Python version"

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.10"
  resolution:
    description: "Resolution strategy"
    required: true
    default: "highest"
  uv-version:
    description: "uv version to use"
    required: true
    default: "0.4.18"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: "true"
        cache-suffix: ${{ inputs.python-version }}

    # - name: Install Python dependencies
    #   # Install eo-tides and all required dependencies.
    #   # --all-extras will install all optional dependencies.
    #   # resolution method will install either "highest""
    #   # versions of dependencies, or "lowest-direct" versions
    #   run: uv sync --all-extras --resolution lowest-direct
    #   shell: bash

    - name: Install Python dependencies
      run: |
        if [ "${{ inputs.resolution }}" == "lowest-direct" ]; then
          uv sync --frozen --all-extras --resolution lowest-direct
        else
          uv sync --frozen --all-extras
        fi
      shell: bash
