name: Draft paper PDF
on:
  push:
    branches:
      - main
      - JOSS_paper
    paths:
      - docs/paper/**
      - .github/workflows/paper.yml

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Generate paper draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: docs/paper/paper.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          # Output path where Pandoc will write the compiled PDF.
          # Note, this should be the same directory as the input
          # paper.md
          path: docs/paper/paper.pdf